vim.wo.relativenumber = true
vim.wo.number = true
vim.opt.cursorline = true
vim.g.mapleader = ' '
vim.o.guifont = '霞鹜文楷等宽:h18'
vim.o.clipboard = 'unnamed'
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
